language:       'go'
go:             ['1.15.x']
env:            ['GO111MODULE=on']
go_import_path: 'zgo.at/zli'
jobs:
  include:
    - {'os': 'linux',   'arch': 'amd64'}
    - {'os': 'linux',   'arch': 'amd64'}
    - {'os': 'linux',   'arch': 'arm64'}
    - {'os': 'linux',   'arch': 'ppc64le'}
    - {'os': 'linux',   'arch': 's390x'}
    - {'os': 'osx',     'arch': 'amd64'}
    - {'os': 'windows', 'arch': 'amd64'}

script: |
  go test -race ./...
